#!/bin/bash
set -ex
# shellcheck source=./ci/test/common
source ./common

delete_dir /tmp/gha-demo
git clone https://github.com/cplee/github-actions-demo /tmp/gha-demo
pushd /tmp/gha-demo
PHONY_SECRET=phony popper run --debug
popd

# test with an action defined on the root of the repo
delete_dir /tmp/npm
git clone https://github.com/actions/npm /tmp/npm
pushd /tmp/npm
DOCKER_USERNAME=foo DOCKER_PASSWORD=bar popper run "Integration Test"
popd

# test with a remote action defined on the root of the repo
init_test_repo
cd $test_repo_path
cat <<EOF > main.workflow
workflow "action on root folder" {
  resolves = "test"
}
action "test" {
  uses = "popperized/ansible@master"
  args = "--version"
  secrets = ["ANSIBLE_SSH_KEY_DATA"]
}
EOF

ANSIBLE_SSH_KEY_DATA="$(echo 'dummydata' | base64)" popper run

# create authenticated access to gitlab
if [ -n "$POPPER_GITLAB_API_TOKEN" ]; then
  GITLAB_REPO_URL="https://oauth2:$POPPER_GITHLAB_API_TOKEN@gitlab.com/barbaragd/action-test@master"
else
  GITLAB_REPO_URL="https://gitlab.com/barbaragd/action-test@master"
fi

# test with actions hosted on gitlab
cd $test_repo_path
cat <<EOF > main.workflow
workflow "clone" {
  resolves = "test"
}
action "test" {
  uses = "$GITLAB_REPO_URL"
}
EOF

popper run
