#!/bin/bash
set -ex

source ./common
init_test_repo
cd $test_repo_path

popper add https://github.com/actions/bin@master
test -f /tmp/mypaper/main.workflow
rm /tmp/mypaper/main.workflow

popper add https://github.com/actions/bin/.github@master
test -f /tmp/mypaper/main.workflow
rm /tmp/mypaper/main.workflow

popper add https://github.com/actions/bin/.github/main.workflow@master
test -f /tmp/mypaper/main.workflow
rm /tmp/mypaper/main.workflow

popper add cplee/github-actions-demo@master
test -f /tmp/mypaper/.github/actions/jshint/Dockerfile
test -f /tmp/mypaper/main.workflow
rm -rf /tmp/mypaper/.github
rm /tmp/mypaper/main.workflow

popper add cplee/github-actions-demo/.github@master
test -f /tmp/mypaper/.github/actions/jshint/Dockerfile
test -f /tmp/mypaper/main.workflow
rm -rf /tmp/mypaper/.github
rm /tmp/mypaper/main.workflow

popper add cplee/github-actions-demo/.github/main.workflow@master
test -f /tmp/mypaper/.github/actions/jshint/Dockerfile
test -f /tmp/mypaper/main.workflow
rm -rf /tmp/mypaper/.github
rm /tmp/mypaper/main.workflow

popper add https://github.com/cplee/github-actions-demo@master
test -f /tmp/mypaper/.github/actions/jshint/Dockerfile
test -f /tmp/mypaper/main.workflow
rm -rf /tmp/mypaper/.github
rm /tmp/mypaper/main.workflow

popper add https://github.com/cplee/github-actions-demo/.github@master
test -f /tmp/mypaper/.github/actions/jshint/Dockerfile
test -f /tmp/mypaper/main.workflow
rm -rf /tmp/mypaper/.github
rm /tmp/mypaper/main.workflow

popper add https://github.com/cplee/github-actions-demo/.github/main.workflow@master
test -f /tmp/mypaper/.github/actions/jshint/Dockerfile
test -f /tmp/mypaper/main.workflow
rm -rf /tmp/mypaper/.github
rm /tmp/mypaper/main.workflow

popper add https://gitlab.com/JayjeetAtGithub/github-actions-demo@master
test -f /tmp/mypaper/.github/actions/jshint/Dockerfile
test -f /tmp/mypaper/main.workflow
rm -rf /tmp/mypaper/.github
rm /tmp/mypaper/main.workflow

popper add https://gitlab.com/JayjeetAtGithub/github-actions-demo/.github@master
test -f /tmp/mypaper/.github/actions/jshint/Dockerfile
test -f /tmp/mypaper/main.workflow
rm -rf /tmp/mypaper/.github
rm /tmp/mypaper/main.workflow

popper add https://gitlab.com/JayjeetAtGithub/github-actions-demo/.github/main.workflow@master
test -f /tmp/mypaper/.github/actions/jshint/Dockerfile
test -f /tmp/mypaper/main.workflow
rm -rf /tmp/mypaper/.github
rm /tmp/mypaper/main.workflow

popper add https://github.com/JayjeetAtGithub/github-actions-demo@develop
test -f /tmp/mypaper/.github/actions/jshint/Dockerfile
test -f /tmp/mypaper/main.workflow
rm -rf /tmp/mypaper/.github
rm /tmp/mypaper/main.workflow

popper add https://github.com/JayjeetAtGithub/github-actions-demo/.github@develop
test -f /tmp/mypaper/.github/actions/jshint/Dockerfile
test -f /tmp/mypaper/main.workflow
rm -rf /tmp/mypaper/.github
rm /tmp/mypaper/main.workflow

popper add https://github.com/JayjeetAtGithub/github-actions-demo/.github/main.workflow@develop
test -f /tmp/mypaper/.github/actions/jshint/Dockerfile
test -f /tmp/mypaper/main.workflow
rm -rf /tmp/mypaper/.github
rm /tmp/mypaper/main.workflow

popper add https://gitlab.com/JayjeetAtGithub/github-actions-demo@develop
test -f /tmp/mypaper/.github/actions/jshint/Dockerfile
test -f /tmp/mypaper/main.workflow
rm -rf /tmp/mypaper/.github
rm /tmp/mypaper/main.workflow

popper add https://gitlab.com/JayjeetAtGithub/github-actions-demo/.github@develop
test -f /tmp/mypaper/.github/actions/jshint/Dockerfile
test -f /tmp/mypaper/main.workflow
rm -rf /tmp/mypaper/.github
rm /tmp/mypaper/main.workflow

popper add https://gitlab.com/JayjeetAtGithub/github-actions-demo/.github/main.workflow@develop
test -f /tmp/mypaper/.github/actions/jshint/Dockerfile
test -f /tmp/mypaper/main.workflow
rm -rf /tmp/mypaper/.github
rm /tmp/mypaper/main.workflow

echo "Popper add command ran successfully !"
