#!/bin/bash
set -ex

source ./common
init_test_repo
popper init

cd $test_repo_path

popper ci --service travis
test -f .travis.yml

popper ci --service circle
test -f .circleci/config.yml

popper ci --service jenkins
test -f Jenkinsfile

popper ci --service gitlab
test -f .gitlab-ci.yml
