#!/bin/bash
set -ex
# shellcheck source=./ci/test/common
source ./common
init_test_repo

cd "$test_repo_path"

popper ci --service travis
test -f .travis.yml
cat .travis.yml

popper ci --service circle
test -f .circleci/config.yml
cat .circleci/config.yml

popper ci --service jenkins
test -f Jenkinsfile
cat Jenkinsfile

popper ci --service gitlab
test -f .gitlab-ci.yml
cat .gitlab-ci.yml

popper ci --service brigade
test -f brigade.js
cat brigade.js

popper ci --service travis --with-singularity
cat .travis.yml

popper ci --service circle --with-singularity
cat .circleci/config.yml

popper ci --service brigade --with-singularity
cat brigade.js

! popper ci --service jenkins --with-singularity

! popper ci --service gitlab --with-singularity


# Test blacklisting/skip in CI environment

export CI=true

cd $test_repo_path

mkdir myaction
cd myaction

touch README.md

cat <<EOF > a.workflow
workflow "wf" {
  resolves = "a"
}
action "a" {
  uses = "sh"
  args = "ls"
}
EOF

cat <<EOF > b.workflow
workflow "wf" {
  resolves = "a"
}
action "a" {
  uses = "sh"
  args = "ls"
}
EOF

cat <<EOF > c.workflow
workflow "wf" {
  resolves = "a"
}
action "a" {
  uses = "sh"
  args = "ls"
}
EOF


git init
git add .
git commit -m "popper:run[/tmp/mypaper/myaction/a.workflow --recursive] popper:run[/tmp/mypaper/myaction/b.workflow]"
popper run --dry-run --runtime "$RUNTIME" > output
grep -q "Found and running workflow at /tmp/mypaper/myaction/a.workflow" output
grep -q "Found and running workflow at /tmp/mypaper/myaction/b.workflow" output
! grep -q "Found and running workflow at /tmp/mypaper/myaction/c.workflow" output

cd $test_repo_path
cd myaction

cat <<EOF > d.workflow
workflow "wf" {
  resolves = "a"
}
action "a" {
  uses = "sh"
  args = "ls"
}
EOF

git add .
git commit -m "Test commit popper:run[/tmp/mypaper/myaction/a.workflow --debug] popper:run[/tmp/mypaper/myaction/d.workflow --quiet]"
popper run --dry-run --runtime "$RUNTIME" > output
grep -q "Found and running workflow at /tmp/mypaper/myaction/a.workflow" output
grep -q "Found and running workflow at /tmp/mypaper/myaction/d.workflow" output
count=$(grep -wc "README.md" output)
test "$count" -eq 1

cd $test_repo_path
cd myaction

cat <<EOF > e.workflow
workflow "wf" {
  resolves = ["a1", "a2"]
}

action "a1" {
  uses = "sh"
  args = "ls"
}

action "a2" {
  uses = "sh"
  args = "ls"
}
EOF

git add .
git commit -m "Test commit 2 popper:run[/tmp/mypaper/myaction/e.workflow --skip a1]"
popper run --dry-run --runtime "$RUNTIME" > output
grep -q "Found and running workflow at /tmp/mypaper/myaction/e.workflow" output
cat output
grep -q "a2" output
! grep -q "a1" output

git clone https://github.com/JayjeetAtGithub/test-repo-for-popper.git
cd test-repo-for-popper
popper run --dry-run --runtime "$RUNTIME" > output
grep -q "Found and running workflow at b.workflow" output

echo "Test CI passed."
