#!/bin/bash
set -ex
# shellcheck source=./ci/test/common
source ./common
init_test_repo

cd "$test_repo_path"

popper ci --service travis
test -f .travis.yml
cat .travis.yml

popper ci --service circle
test -f .circleci/config.yml
cat .circleci/config.yml

popper ci --service jenkins
test -f Jenkinsfile
cat Jenkinsfile

popper ci --service gitlab
test -f .gitlab-ci.yml
cat .gitlab-ci.yml

popper ci --service travis --with-singularity
test -f .travis.yml
cat .travis.yml

popper ci --service circle --with-singularity
test -f .circleci/config.yml
cat .circleci/config.yml

! popper ci --service jenkins --with-singularity

! popper ci --service gitlab --with-singularity


# Test blacklisting/skip in CI environment

export CI=true

cd $test_repo_path

mkdir myaction
cd myaction

touch README.md

cat <<EOF > a.workflow
workflow "wf" {
  resolves = "a"
}

action "a" {
  uses = "sh"
  args = "ls"
}
EOF

cat <<EOF > b.workflow
workflow "wf" {
  resolves = "a"
}

action "a" {
  uses = "sh"
  args = "ls"
}
EOF

cat <<EOF > c.workflow
workflow "wf" {
  resolves = "a"
}

action "a" {
  uses = "sh"
  args = "ls"
}
EOF



git init
git add .
git commit -m "popper:whitelist[/tmp/mypaper/myaction/a.workflow,/tmp/mypaper/myaction/b.workflow]"
popper run | grep "Only running workflows: /tmp/mypaper/myaction/a.workflow, /tmp/mypaper/myaction/b.workflow"


cd $test_repo_path
cd myaction

cat <<EOF > d.workflow
workflow "wf" {
  resolves = "a"
}

action "a" {
  uses = "sh"
  args = "ls"
}
EOF

git add .
git commit -m "popper:skip[/tmp/mypaper/myaction/a.workflow,/tmp/mypaper/myaction/c.workflow"]
popper run | grep "Only running workflows: /tmp/mypaper/myaction/b.workflow, /tmp/mypaper/myaction/d.workflow"