#!/bin/bash
set -e

export test_repo_path=/tmp/mypaper

function delete_dir {
  set +e
  if ! rm -rf "$1"; then
    # try to remove using docker
    docker run --rm -v /tmp:/tmp alpine:3.8 rm -rf "$1"
  fi
  set -e
}

function init_test_repo {
  if [ "$POPPER_TEST_MODE" == "with-git" ]
  then
    delete_dir $test_repo_path
    mkdir $test_repo_path
    pushd $test_repo_path
    git init
    echo 'foo' > README.md
    git add .
    git commit -m 'first'
    popd
  else
    delete_dir $test_repo_path
    mkdir $test_repo_path
    pushd $test_repo_path
    echo 'foo' > README.md
    popd
  fi
}

function send_sigint {
  # shellcheck disable=SC2086
  { setsid $1; } &
  subshell_pid=$!
  pids=$(ps -ax -o ppid,pid --no-headers | sed -r 's/^ +//g;s/ +/ /g' |
                           grep "^$subshell_pid " | cut -f 2 -d " ")

  sleep "$2"

  for child in $pids;  do
    kill -SIGINT "-$child"
  done
  wait $subshell_pid
}
