#!/bin/bash
set -ex
# shellcheck source=./ci/test/common
source ./ci/test/common
init_test_repo
cd "$test_repo_path"

## Testing default file feature
git clone https://github.com/popperized/github-actions-demo.git
cd github-actions-demo

popper dot --wfile .github/main.workflow > dot_output

grep "digraph G .* graph" dot_output
grep "\"branch-filter\" -> \"deploy\";" dot_output
grep "\"install\" -> \"lint\";" dot_output
grep "\"install\" -> \"test\";" dot_output
grep "\"lint\" -> \"branch-filter\";" dot_output
grep "\"test-and-deploy\" -> \"install\";" dot_output
grep "\"test\" -> \"branch-filter\";" dot_output

## Testing wfile argument feature
cd "$test_repo_path"
rm -rf github-actions-demo
git clone https://github.com/popperized/github-actions-demo.git
popper dot --wfile github-actions-demo/.github/main.workflow > dot_output

grep "digraph G .* graph" dot_output
grep "\"branch-filter\" -> \"deploy\";" dot_output
grep "\"install\" -> \"lint\";" dot_output
grep "\"install\" -> \"test\";" dot_output
grep "\"lint\" -> \"branch-filter\";" dot_output
grep "\"test-and-deploy\" -> \"install\";" dot_output
grep "\"test\" -> \"branch-filter\";" dot_output

# test no color
(! grep ".*\"test-and-deploy\".*,color=" dot_output)

# test with color
popper dot --colors --wfile github-actions-demo/.github/main.workflow > dot_output
grep ".*\"test-and-deploy\".*,color=" dot_output

echo "Test DOT passed."
