#!/bin/bash
set -ex
# shellcheck source=./ci/test/common
source ./ci/test/common
init_test_repo
cd "$test_repo_path"

## `--dry-run` test for DockerRunner

git clone https://github.com/popperized/github-actions-demo
cd github-actions-demo
git checkout c824a5a

export PHONY_SECRET=foo

dry_num_lines=$(popper run --wfile .github/main.workflow --dry-run --engine "$ENGINE" | grep -c 'DRYRUN')

# 5 actions, at least one line per action
test "$dry_num_lines" -gt 5

echo "Test DRY-RUN passed."
