#!/bin/bash
set -ex
# shellcheck source=./ci/test/common
source ./ci/test/common
init_test_repo
cd "$test_repo_path"

# write the workflow file
cat <<EOF > main.workflow
workflow "test" {
    resolves = "run"
}

action "run" {
    uses = "popperized/bin/sh@master"
    args = ["hostname"]
}
EOF

# config file called settings.yml in the project root.
cat <<EOF > settings.yml
engine:
  name: docker
  options:
    image: abc/xyz
    hostname: xYz.local
EOF

popper run --wfile main.workflow --conf settings.yml > output
grep -Fxq "xYz.local" output

popper run --wfile main.workflow > output
grep -vFxq "xYz.local" output

# config file with different name in the project root.
cat <<EOF > myconf.yml
engine:
  name: docker
  options:
    image: abc/xyz
    hostname: xYz.local
EOF

popper run --wfile main.workflow --conf myconf.yml > output
grep -Fxq "xYz.local" output

popper run --wfile main.workflow > output
grep -vFxq "xYz.local" output

# config file in different directory than project root.
mkdir -p /tmp/myengineconf/
cat <<EOF > /tmp/myengineconf/mysettings.yml
engine:
  name: docker
  options:
    image: abc/xyz
    hostname: xYz.local
EOF

popper run --wfile main.workflow --conf /tmp/myengineconf/mysettings.yml > output
grep -Fxq "xYz.local" output

popper run --wfile main.workflow > output
grep -vFxq "xYz.local" output

cat <<EOF > settings
engine:
  name: docker
  options:
    image: abc/xyz
    hostname: xYz.local
EOF

popper run --wfile main.workflow --conf settings && exit 1

popper run --wfile main.workflow --conf conf && exit 1

# fail since engine config has no name attribute
cat <<EOF > settings.yml
engine:
  options:
    image: abc/xyz
    hostname: xYz.local
EOF

popper run --wfile main.workflow --conf settings.yml && exit 1

# fail since resource manager config has no name attribute
cat <<EOF > settings.yml
engine:
  name: docker
  options:
    image: abc/xyz
    hostname: xYz.local

resource_manager:
  options:
    foo: bar
EOF

popper run --wfile main.workflow --conf settings.yml && exit 1

echo "Test ENGINE-CONF passed."
