#!/bin/bash
set -ex
# shellcheck source=./ci/test/common
source ./ci/test/common
init_test_repo
cd "$test_repo_path"

# write the workflow file
cat <<EOF > main.workflow
workflow "test" {
    resolves = "run"
}

action "run" {
    uses = "popperized/bin/sh@master"
    args = ["hostname"]
}
EOF

# config file called settings.py in the project root.
cat <<EOF > settings.py
ENGINE = {
    "name": "dont use this name",
    "image": "abc/xyz",
    "hostname": "xYz.local"
}
EOF

popper run --wfile main.workflow --conf settings.py > output
grep -Fxq "xYz.local" output

popper run --wfile main.workflow > output
grep -vFxq "xYz.local" output

# config file with different name in the project root.
cat <<EOF > myconf.py
ENGINE = {
    "name": "dont use this name",
    "image": "abc/xyz",
    "hostname": "xYz.local"
}
EOF

popper run --wfile main.workflow --conf myconf.py > output
grep -Fxq "xYz.local" output

popper run --wfile main.workflow > output
grep -vFxq "xYz.local" output

# config file in different directory than project root.
mkdir -p /tmp/myengineconf/
cat <<EOF > /tmp/myengineconf/mysettings.py
ENGINE = {
    "name": "dont use this name",
    "image": "abc/xyz",
    "hostname": "xYz.local"
}
EOF

popper run --wfile main.workflow --conf /tmp/myengineconf/mysettings.py > output
grep -Fxq "xYz.local" output

popper run --wfile main.workflow > output
grep -vFxq "xYz.local" output

cat <<EOF > settings
ENGINE = {
    "name": "dont use this name",
    "image": "abc/xyz",
    "hostname": "xYz.local"
}
EOF

popper run --wfile main.workflow --conf settings && exit 1

popper run --wfile main.workflow --conf conf && exit 1

cat <<EOF > newconf.py
print('No config')
EOF

popper run --wfile main.workflow --conf newconf.py && exit 1

echo "Test ENGINE-CONF passed."
