#!/usr/bin/env bash
set -ex
# shellcheck source=./ci/test/common
source ./common
init_test_repo
cd "$test_repo_path"

cat <<EOF > main.workflow
workflow "wf" {
  resolves = "d"
}

action "a" {
  uses = "sh"
  args = "ls"
}

action "b" {
  needs = ["a"]
  uses = "sh"
  args = "ls"
}

action "c" {
  needs = ["b"]
  uses = "sh"
  args = "ls"
}
EOF

cat <<EOF > inject-pre.workflow
workflow "wf" {
  resolves = "pre"
}

action "pre" {
  uses = "sh"
  args = "echo pre-action"
}

EOF


cat <<EOF > inject-post.workflow
workflow "wf" {
  resolves = "post"
}

action "post" {
  uses = "sh"
  args = "echo post-action"
}

EOF

cat <<EOF > inject-both.workflow
workflow "wf" {
  resolves = "post"
}
action "pre" {
  uses = "sh"
  args = "echo pre-action"
}

action "post" {
  uses = "sh"
  args = "echo post-action"
}

EOF

popper run --dry-run main.workflow --inject-actions-from inject-pre.workflow  | grep "pre-action"
popper run --dry-run main.workflow --inject-actions-from inject-post.workflow  | grep "post-action"
popper run --dry-run main.workflow --inject-actions-from inject-both.workflow  | grep "pre-action"
popper run --dry-run main.workflow --inject-actions-from inject-both.workflow  | grep "post-action"

echo "Test INJECT ACTIONS passed."