#!/bin/bash
set -ex
# shellcheck source=./ci/test/common
source ./common
init_test_repo
cd "$test_repo_path"

cat <<EOF > main.workflow 
workflow "sample" {
    resolves = "test"
}

action "test" {
    uses = "docker://busybox"
    args = ["ls", "-ltr"]
}
EOF

output_lines_without_quiet=$(popper run --runtime "$RUNTIME" | wc -l)
output_lines_with_quiet=$(popper run --quiet --runtime "$RUNTIME" | wc -l)

test "$output_lines_without_quiet" -gt "$output_lines_with_quiet"
