#!/bin/bash
set -ex

source ./common
init_test_repo
cd $test_repo_path

function create_workflow(){
    cat > $1 << EOF
workflow "test" {
  resolves = "show env"
}

action "show env" {
  uses = "actions/bin/sh@master"
  args = "ls"
}
EOF
}

mkdir another
mkdir another/another

workflows=( "main.workflow" "another/main.workflow" "another/another/main.workflow" "try.workflow" "another/demo.workflow" )

for i in "${workflows[@]}"
do
    create_workflow $i
done

popper run --recursive