#!/bin/bash
set -ex
# shellcheck source=./ci/test/common
source ./ci/test/common
init_test_repo
cd "$test_repo_path"

# generate the workfow id
cat <<EOF > id.py
import os
import hashlib
identifier = str(os.getuid()) + "_main.workflow"
id = str(hashlib.md5(identifier.encode()).hexdigest())
print(id)
EOF

ID=$(python id.py 2>&1)

cat <<EOF > main.workflow
workflow "test" {
  resolves = "show env"
}

action "show env" {
  uses = "popperized/bin/sh@master"
  args = "ls"
}
EOF

popper run

docker ps -a | grep 'popper_show_env'

docker cp ./main.workflow popper_show_env_"$ID":/

popper run --reuse

# the file we copied above should still be there
docker cp popper_show_env_"$ID":/main.workflow main.workflow

# now we re-run without --reuse so a new container is created
popper run

# so the file shouldn't be there
(! docker cp popper_show_env_"$ID":/main.workflow /tmp/main.workflow)

# lastly, test reuse for a single action
popper run --reuse 'show env'

# test while reusing the container uses the updated args.

if [ "$ENGINE" != "singularity" ]; then

cat <<EOF > main.workflow
workflow "test" {
  resolves = "show env"
}

action "show env" {
  uses = "popperized/bin/sh@master"
  args = "ls"
  env = {
    MESSAGE = "message in a bottle"
  }
}
EOF

popper run --engine "$ENGINE" > output

grep -q "README.md" output
grep -q "main.workflow" output

cat <<EOF > main.workflow
workflow "test" {
  resolves = "show env"
}

action "show env" {
  uses = "popperized/bin/sh@master"
  runs = ["sh", "-c", "echo \$MESSAGE"]
}
EOF

popper run --reuse --engine "$ENGINE" > output
grep  -q "message in a bottle" output

cat <<EOF > main.workflow
workflow "test" {
  resolves = "check file"
}

action "check file" {
  uses = "popperized/bin/sh@master"
  runs = ["sh", "-c", "echo 'Hello from Popper 2.x !' > /usr/local/popper.file"]
}
EOF

popper run --engine "$ENGINE" > /dev/null

cat <<EOF > main.workflow
workflow "test" {
  resolves = "check file"
}

action "check file" {
  uses = "popperized/bin/sh@master"
  runs = ["sh", "-c", "cat /usr/local/popper.file"]
}
EOF

popper run --reuse --engine "$ENGINE" > output
grep -q "Hello from Popper 2.x !" output

fi

echo "Test REUSE passed."
