#!/bin/bash
set -ex
# shellcheck source=./ci/test/common
source ./common
init_test_repo
cd "$test_repo_path"

git clone https://github.com/popperized/spack
pushd spack
popper run .ci/test.workflow --runtime "$RUNTIME"
popd

echo "Test SAMPLES passed."