#!/bin/bash
set -ex
# shellcheck source=./ci/test/common
source ./ci/test/common
init_test_repo
cd "$test_repo_path"

popper scaffold

test -f wf.yml

popper run -f wf.yml

echo "Test SCAFFOLD passed."
