#!/bin/bash
set -ex
# shellcheck source=./ci/test/common
source ./common
init_test_repo
cd "$test_repo_path"

popper scaffold

test -f main.workflow
test -f actions/example/Dockerfile
test -f actions/example/entrypoint.sh
test -f actions/example/README.md

popper run --runtime "$RUNTIME"

mkdir -p pipelines/mypipe
cd pipelines/mypipe

popper scaffold

test -f main.workflow
test -f actions/example/Dockerfile
test -f actions/example/entrypoint.sh
test -f actions/example/README.md

echo "Test SCAFFOLD passed."