#!/bin/bash
set -ex

source ./common
init_test_repo
cd $test_repo_path

cat <<EOF > main.workflow
workflow "test" {
  resolves = "show env"
}

action "show env" {
  uses = "actions/bin/sh@master"
  args = "ls"
}
EOF

popper run --serial
