#!/bin/bash
set -ex

source ./common
init_test_repo
cd $test_repo_path

mkdir actions
mkdir actions/example

export SECRET_KEY=1234

cat <<EOF > actions/example/singularity.def
Bootstrap: docker
From: ubuntu:14.04

%runscript
echo 'Entered runscript'
echo \$F_NAME
echo \$L_NAME
echo \$SECRET_KEY
sh -c \$@
EOF

cat <<EOF > main.workflow
workflow "test" {
  resolves = ["custom"]
}

action "busybox" {
  uses = "shub://singularityhub/centos"
}

action "custom" {
  uses = "./actions/example"
  args = ["ls -a"]
  secrets = ["SECRET_KEY"]
  env = {
    F_NAME = "first_name",
    L_NAME = "last_name"
  }
  needs = [
    "busybox"
  ]
}
EOF

popper run