#!/bin/bash
set -ex
# shellcheck source=./ci/test/common
source ./common
init_test_repo
cd "$test_repo_path"

cat <<EOF > main.workflow
workflow "wf" {
  resolves = "d"
}

action "a1" {
  uses = "sh"
  args = "ls"
}

action "a2" {
  uses = "sh"
  args = "ls"
}

action "b" {
  needs = ["a1", "a2"]
  uses = "sh"
  args = "ls"
}

action "c" {
  needs = ["a1", "a2"]
  uses = "sh"
  args = "ls"
}

action "d" {
  needs = ["b", "c"]
  uses = "sh"
  args = "ls"
}
EOF

popper run --dry-run a1 | grep "a1"
popper run --dry-run a2 | grep "a2"
popper run --dry-run b | grep "b"
popper run --dry-run c | grep "c"
popper run --dry-run d | grep "d"

! popper run --dry-run --skip e1
! popper run --dry-run --skip a1 --skip a2
popper run --dry-run --skip a1 > output
grep -q "a2" output
grep -q "b" output
grep -q "c" output
grep -q "d" output
popper run --dry-run --skip a2 > output
grep -q "a1" output
grep -q "b" output
grep -q "c" output
grep -q "d" output
! popper run --dry-run --skip b --skip c
popper run --dry-run --skip b > output
grep -q "a1" output
grep -q "a2" output
grep -q "c" output
grep -q "d" output
popper run --dry-run --skip c > output
grep -q "a1" output
grep -q "a2" output
grep -q "b" output
grep -q "d" output
popper run --dry-run --skip d > output
grep -q "a1" output
grep -q "a2" output
grep -q "b" output
grep -q "c" output

cat <<EOF > main.workflow
workflow "wf" {
  resolves = "wrong"
}

action "a1" {
  uses = "sh"
  args = "ls"
}

action "a2" {
  uses = "sh"
  args = "ls"
}

action "b" {
  needs = ["a1", "a2"]
  uses = "sh"
  args = "ls"
}

action "c" {
  needs = ["a1", "a2"]
  uses = "sh"
  args = "ls"
}

action "d" {
  needs = ["b", "c"]
  uses = "sh"
  args = "ls"
}
EOF

! popper run --dry-run

cat <<EOF > main.workflow
workflow "wf" {
  resolves = "d"
}

action "a1" {
  uses = "sh"
  args = "ls"
}

action "a2" {
  uses = "sh"
  args = "ls"
}

action "b" {
  needs = ["a1", "a2"]
  uses = "sh"
  args = "ls"
}

action "c" {
  needs = ["a1", "a2"]
  uses = "sh"
  args = "ls"
}

action "d" {
  needs = ["b1", "c"]
  uses = "sh"
  args = "ls"
}
EOF

! popper run --dry-run