#!/bin/bash
set -ex
# shellcheck source=./ci/test/common
source ./common
init_test_repo
cd "$test_repo_path"

cat <<EOF > main.workflow
workflow "wf" {
  resolves = "d"
}

action "a1" {
  uses = "sh"
  args = "ls"
}

action "a2" {
  uses = "sh"
  args = "ls"
}

action "b" {
  needs = ["a1", "a2"]
  uses = "sh"
  args = "ls"
}

action "c" {
  needs = ["a1", "a2"]
  uses = "sh"
  args = "ls"
}

action "d" {
  needs = ["b", "c"]
  uses = "sh"
  args = "ls"
}
EOF

! popper run a1 --skip a2

popper run --dry-run --runtime "$RUNTIME" a1 | grep "a1"
popper run --dry-run --runtime "$RUNTIME" a2 | grep "a2"
popper run --dry-run --runtime "$RUNTIME" b | grep "b"
popper run --dry-run --runtime "$RUNTIME" c | grep "c"
popper run --dry-run --runtime "$RUNTIME" d | grep "d"

! popper run --dry-run --skip e1
! popper run --dry-run --skip a1 --skip a2
popper run --dry-run --runtime "$RUNTIME" --skip a1 > output
grep -q "a2" output
grep -q "b" output
grep -q "c" output
grep -q "d" output
popper run --dry-run --runtime "$RUNTIME" --skip a2 > output
grep -q "a1" output
grep -q "b" output
grep -q "c" output
grep -q "d" output
! popper run --dry-run --runtime "$RUNTIME" --skip b --skip c
popper run --dry-run --runtime "$RUNTIME" --skip b > output
grep -q "a1" output
grep -q "a2" output
grep -q "c" output
grep -q "d" output
popper run --dry-run --runtime "$RUNTIME" --skip c > output
grep -q "a1" output
grep -q "a2" output
grep -q "b" output
grep -q "d" output
popper run --dry-run --runtime "$RUNTIME" --skip d > output
grep -q "a1" output
grep -q "a2" output
grep -q "b" output
grep -q "c" output

cat <<EOF > main.workflow
workflow "wf" {
  resolves = "wrong"
}

action "a1" {
  uses = "sh"
  args = "ls"
}

action "a2" {
  uses = "sh"
  args = "ls"
}

action "b" {
  needs = ["a1", "a2"]
  uses = "sh"
  args = "ls"
}

action "c" {
  needs = ["a1", "a2"]
  uses = "sh"
  args = "ls"
}

action "d" {
  needs = ["b", "c"]
  uses = "sh"
  args = "ls"
}
EOF

! popper run --dry-run --runtime "$RUNTIME"

cat <<EOF > main.workflow
workflow "wf" {
  resolves = "d"
}

action "a1" {
  uses = "sh"
  args = "ls"
}

action "a2" {
  uses = "sh"
  args = "ls"
}

action "b" {
  needs = ["a1", "a2"]
  uses = "sh"
  args = "ls"
}

action "c" {
  needs = ["a1", "a2"]
  uses = "sh"
  args = "ls"
}

action "d" {
  needs = ["b1", "c"]
  uses = "sh"
  args = "ls"
}
EOF

! popper run --dry-run --runtime "$RUNTIME"

echo "Test SKIP passed."