#!/bin/bash
set -ex
# shellcheck source=./ci/test/common
source ./ci/test/common
init_test_repo
cd "$test_repo_path"

cat <<EOF > main.workflow
workflow "wf" {
  resolves = "b"
}

action "b" {
  uses = "\$_VAR1"
  args = "\$_VAR2"
}
EOF

(! popper run --wfile main.workflow --substitution)
popper run --wfile main.workflow --dry-run --substitution _VAR1=sh --substitution _VAR2=ls --engine "$ENGINE" | grep "ls"
(! popper run --wfile main.workflow --dry-run --substitution _VAR1=shx --substitution _VAR2=ls --engine "$ENGINE")
popper run --wfile main.workflow --dry-run --substitution _VAR1=shx --substitution _VAR1=sh --substitution _VAR2=ls --engine "$ENGINE" | grep "ls"

export TESTING="test"
cat <<EOF > main.workflow
workflow "wf" {
  resolves = "c"
}

action "b" {
  uses = "sh"
  args = "ls"
}

action "c" {
  needs = "b"
  uses = "sh"
  args = ["ls","\$_VAR1"]
  runs = "\$_VAR2"
  secrets = ["\$_VAR3"]
  env = {
    "\$_VAR4" = "\$_VAR5"
  }
}
EOF

popper run --wfile main.workflow --dry-run --substitution _VAR1=pwd --substitution _VAR2=ubuntu-latest --substitution _VAR3=TESTING --substitution _VAR4=TEST_ENV --substitution _VAR5=TEST --engine "$ENGINE" | grep "ls pwd"
(! popper run --wfile main.workflow --dry-run --substitution _VAR1=pwd --substitution _VAR2=ubuntu-latest --substitution _VAR3=TESTING --substitution _VAR4=TEST_ENV --substitution _VAR5=TEST --substitution _VAR6=EXTRA --engine "$ENGINE" | grep "ls pwd")
popper run --wfile main.workflow --dry-run --substitution _VAR1=pwd --substitution _VAR2=ubuntu-latest --substitution _VAR3=TESTING --substitution _VAR4=TEST_ENV --substitution _VAR5=TEST --substitution _VAR6=EXTRA --allow-loose --engine "$ENGINE" | grep "ls pwd"
(! popper run --wfile main.workflow --dry-run --substitution _VAR1=pwd --substitution _VAR2=ubuntu-latest --substitution _VAR3=TESTING --substitution _VAR4=TEST_ENV --substitution _VAR5=TEST --substitution _var6=EXTRA --engine "$ENGINE" | grep "ls pwd")

cat <<EOF > main.workflow
workflow "wf" {
  resolves = "b"
}

action "a" {
  uses = "\$_VAR1"
  args = "\$_VAR2"
}

action "b" {
  needs = "\$_VAR3"
  uses = "\$_VAR1"
  args = "\$_VAR2"
}
EOF

popper run --wfile main.workflow --dry-run --substitution _VAR1=sh --substitution _VAR2=ls --substitution _VAR3=a --engine "$ENGINE"
(! popper run --wfile main.workflow --dry-run --substitution _VAR1=sh --substitution _VAR2=ls --substitution _VAR3=a --substitution _VAR4=extra --engine "$ENGINE")
popper run --wfile main.workflow --dry-run --substitution _VAR1=sh --substitution _VAR2=ls --substitution _VAR3=a --substitution _VAR4=extra --allow-loose --engine "$ENGINE"

echo "Test substitution passed."
