steps:
- id: skip on forks
  uses: docker://docker:19.03.3
  runs: [sh, -exc]
  secrets: [ENGINE, TRAVIS_PYTHON_VERSION, TRAVIS_PULL_REQUEST]
  args:
  - |
    # skip if this is a build for a PR
    # for the rest, only continue if build:
    #   1. is for upstream (getpopper/popper) repo
    #   2. corresponds to the docker,python-3.7 element of the matrix
    if [[ "$TRAVIS_PULL_REQUEST" != "false" ]] ||
       [[ "$GIT_REMOTE_ORIGIN_URL" != "https://github.com/getpopper/popper.git" ]] ||
       [[ "$GIT_BRANCH" != "master" ]] ||
       [[ "$ENGINE" != "docker" ]] ||
       [[ "$TRAVIS_PYTHON_VERSION" != "3.7" ]]; then
      exit 78
    fi

- id: build docker image
  uses: docker://docker:19.03
  runs: [sh, -ec]
  args:
  - |
    docker build -t getpopper/popper:latest src/

    if [ -n "$GIT_TAG" ]; then
      docker tag getpopper/popper:latest getpopper/popper:$GIT_TAG
    fi

- id: push image
  uses: docker://docker:19.03.3
  secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
  runs: [sh, -ec]
  args:
  - |
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    docker push getpopper/popper:latest

    if [ -n "$GIT_TAG" ]; then
      docker push getpopper/popper:$GIT_TAG
    fi
