#!/usr/bin/env bash
set -e

rm -f .dockerignore
cat << EOF > .dockerignore
.DS_Store
.dockerignore
.git/
.gitignore
.gitmodules
.popper.yml
.ropeproject/
.sass-cache/
.travis.yml
.vendor/
CODE_OF_CONDUCT.md
CONTRIBUTING.md
Dockerfile
LICENSE
README.md
ci/
doc/
docs/
envs/
popper/
wiki/
EOF

for d in envs/* ; do
  if [ ! -d $d ]; then
    continue
  fi
  if [ "$d" == 'envs/jenkins' ]; then
    continue
  fi
  echo "############"
  echo "# Building $(basename $d)"
  echo "############"
  cp $d/Dockerfile .
  docker build -t falsifiable/popper:$(basename $d) .
  rm Dockerfile
done
rm -f .dockerignore
